basePath: /
host: localhost:8082
info:
  contact: {}
  description: Service for managing user subscriptions
  title: Subscription Service
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Subscription
    type: apiKey
swagger: "2.0"
